openapi: 3.0.3
info:
  title: Telegram Payments Backend API
  version: 0.1.0
  description: Draft schema for future endpoints. Keep this file updated with any API changes.
servers:
  - url: /api
paths:
  /status:
    get:
      summary: API status check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  status:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
  /auth/login:
    post:
      summary: Admin login (draft)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: JWT token issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  token:
                    type: string
        '401':
          description: Unauthorized
  /auth/me:
    get:
      summary: Get current admin profile (draft)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile
  /settings:
    get:
      summary: Get bot/payment settings (draft)
      responses:
        '200':
          description: Settings
    put:
      summary: Update bot/payment settings (draft)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Updated settings
  /telegram/webhook:
    post:
      summary: Telegram webhook endpoint (draft)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Acknowledged
  /telegram/set-webhook:
    post:
      summary: Set Telegram webhook URL (draft)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        '200':
          description: Result
  /payments:
    get:
      summary: List payments (draft)
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, paid, failed, canceled]
        - name: limit
          in: query
          schema:
            type: integer
        - name: offset
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: List of payments
  /subscribers:
    get:
      summary: List subscribers (draft)
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [active, expired, revoked, pending]
      responses:
        '200':
          description: List of subscribers
  /stats/summary:
    get:
      summary: Summary statistics (draft)
      parameters:
        - name: from
          in: query
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Aggregated stats
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
